services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - PORT=5173
    command: npm run dev -- --host

  backend:
    build: ./backend
    ports:
      - "3005:3005"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=3005
    command: node index.js